id: A78EA420D
base_file: fDE93.txt
type: translation
source_metadata:
  languages:
  - en
  - bo
  datatype: PlainText
  created_at: 2022-06-11 13:14:17.244812
  last_modified_at: 2022-06-11 13:14:17.244820
